<a href="https://colab.research.google.com/github/aeshikaz/ML-lab/blob/main/lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [ ]:
b = np.array([[1, 2, 3],
              [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [1]:
import numpy as np

zeros = np.zeros((3, 4))
ones = np.ones((2, 5))

print("3x4 Matrix of Zeros:")
print(zeros)
print("Shape:", zeros.shape)

print("\n2x5 Matrix of Ones:")
print(ones)
print("Shape:", ones.shape)

3x4 Matrix of Zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Shape: (3, 4)

2x5 Matrix of Ones:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Shape: (2, 5)


In [3]:
import numpy as np

arr = np.arange(1, 13)
print("Original Array:", arr)
print("Shape:", arr.shape)

reshaped = arr.reshape(3, 4)
print("\nReshaped 3x4 Matrix:")
print(reshaped)
print("Shape:", reshaped.shape)

Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Shape: (12,)

Reshaped 3x4 Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)


In [ ]:
c = np.array([1, 2, 3], dtype=float)
print(c)

[1. 2. 3.]


In [4]:
import numpy as np

arr = np.random.randint(1, 100, size=10)
print("Array:", arr)

print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))
print("Mean:", np.mean(arr))
print("Sum:", np.sum(arr))

Array: [ 7  3 71 87 51 58 55 52 75 14]
Minimum: 3
Maximum: 87
Mean: 47.3
Sum: 473


In [5]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Eve"],
    "Marks": [85, 90, 78, 92, 88]
}

df = pd.DataFrame(data)
print(df)
print("\nData Types:")
print(df.dtypes)

      Name  Marks
0    Alice     85
1      Bob     90
2  Charlie     78
3    Diana     92
4      Eve     88

Data Types:
Name     object
Marks     int64
dtype: object


In [7]:
import pandas as pd
from google.colab import drive

drive.mount('/content/drive')

df = pd.read_csv("/content/Wholesale customers data.csv")

print("First 5 records:")
print(df.head())

print("\nLast 5 records:")
print(df.tail())

Mounted at /content/drive
First 5 records:
   Channel  Region  Fresh  Milk  Grocery  Frozen  Detergents_Paper  Delicassen
0        2       3  12669  9656     7561     214              2674        1338
1        2       3   7057  9810     9568    1762              3293        1776
2        2       3   6353  8808     7684    2405              3516        7844
3        1       3  13265  1196     4221    6404               507        1788
4        2       3  22615  5410     7198    3915              1777        5185

Last 5 records:
     Channel  Region  Fresh   Milk  Grocery  Frozen  Detergents_Paper  \
435        1       3  29703  12051    16027   13135               182   
436        1       3  39228   1431      764    4510                93   
437        2       3  14531  15488    30243     437             14841   
438        1       3  10290   1981     2232    1038               168   
439        1       3   2787   1698     2510      65               477   

     Delicassen  
435      

In [8]:
import pandas as pd
from google.colab import drive

drive.mount('/content/drive')

df = pd.read_csv("/content/Wholesale customers data.csv")

print("Dataset Info:")
df.info()

print("\nNumber of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])

print("\nMissing Values per Column:")
print(df.isnull().sum())

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 440 entries, 0 to 439
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Channel           440 non-null    int64
 1   Region            440 non-null    int64
 2   Fresh             440 non-null    int64
 3   Milk              440 non-null    int64
 4   Grocery           440 non-null    int64
 5   Frozen            440 non-null    int64
 6   Detergents_Paper  440 non-null    int64
 7   Delicassen        440 non-null    int64
dtypes: int64(8)
memory usage: 27.6 KB

Number of Rows: 440
Number of Columns: 8

Missing Values per Column:
Channel             0
Region              0
Fresh               0
Milk                0
Grocery             0
Frozen              0
Detergents_Paper    0
Delicassen          0
dtype: int64


In [9]:
import pandas as pd
from google.colab import drive

drive.mount('/content/drive')

df = pd.read_csv("/content/Wholesale customers data.csv")

print("Statistical Summary:")
print(df.describe())

print("""
Interpretation:
- mean   : average value of each column
- std    : how spread out the values are
- min    : smallest value in the column
- max    : largest value in the column
- 25/50/75%: quartile distribution of the data
""")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Statistical Summary:
          Channel      Region          Fresh          Milk       Grocery  \
count  440.000000  440.000000     440.000000    440.000000    440.000000   
mean     1.322727    2.543182   12000.297727   5796.265909   7951.277273   
std      0.468052    0.774272   12647.328865   7380.377175   9503.162829   
min      1.000000    1.000000       3.000000     55.000000      3.000000   
25%      1.000000    2.000000    3127.750000   1533.000000   2153.000000   
50%      1.000000    3.000000    8504.000000   3627.000000   4755.500000   
75%      2.000000    3.000000   16933.750000   7190.250000  10655.750000   
max      2.000000    3.000000  112151.000000  73498.000000  92780.000000   

             Frozen  Detergents_Paper    Delicassen  
count    440.000000        440.000000    440.000000  
mean    3071.931818       2881.493182   1524.870455  
std